const seed=[{id:1,user:'Mithilesh',to:'Rahul',title:'Beat my night photo 📸',desc:'Click a better night photo and tag the next friend.',likes:128,dislikes:9,comments:24,attempts:17,chain:8,trending:true},{id:2,user:'Aman',to:'Priya',title:'20-second beat challenge 🎵',desc:'Make a better 20-second beat. Any style allowed.',likes:94,dislikes:4,comments:13,attempts:11,chain:5,trending:true},{id:3,user:'Sara',to:'Ravi',title:'Best chai plating ☕',desc:'Make your chai look better than mine.',likes:57,dislikes:3,comments:8,attempts:6,chain:3,trending:false}];
let challenges=JSON.parse(localStorage.getItem('bt_challenges')||'null')||seed;let coins=+localStorage.getItem('bt_coins')||250;let owned=JSON.parse(localStorage.getItem('bt_owned')||'[]');
const shopItems=[['🔥 Fire Reaction Pack',100,'7 days'],['⚡ Animated Profile Frame',300,'30 days'],['🌌 Neon Challenge Theme',250,'30 days'],['🏆 Legendary Trophy',2000,'Permanent']];
function save(){localStorage.setItem('bt_challenges',JSON.stringify(challenges));localStorage.setItem('bt_coins',coins);localStorage.setItem('bt_owned',JSON.stringify(owned));document.querySelector('#coins').textContent=coins}
function render(list=challenges){document.querySelector('#feed').innerHTML=list.map(c=>`<article class='card'><div class='meta'>${c.user} challenged ${c.to||'a friend'} • Generation ${c.chain}</div><h3>${c.title}</h3><div class='challenge'>${c.desc}</div><div class='stats'><button onclick='react(${c.id},"likes")'>❤️ ${c.likes}</button><button onclick='react(${c.id},"dislikes")'>👎 ${c.dislikes}</button><button onclick='comment(${c.id})'>💬 ${c.comments}</button><button class='primary' onclick='beat(${c.id})'>🔥 BEAT IT</button><button onclick='tag(${c.id})'>👥 TAG FRIEND</button></div><div class='chain'>⛓ ${c.attempts} attempts • ${c.chain} generations</div></article>`).join('')}
function react(id,k){let c=challenges.find(x=>x.id===id);c[k]++;save();render()}
function comment(id){let t=prompt('Write a comment');if(t){let c=challenges.find(x=>x.id===id);c.comments++;coins+=2;save();render();alert('Comment added • +2 coins')}}
function beat(id){let c=challenges.find(x=>x.id===id);let proof=prompt('Describe your attempt/proof for V1');if(proof){c.attempts++;coins+=20;save();render();alert('Attempt submitted 🔥 +20 coins. Now tag a friend to continue the chain.')}}
function tag(id){let n=prompt('Friend name to tag');if(n){let c=challenges.find(x=>x.id===id);c.chain++;coins+=5;save();render();alert(`Challenge passed to ${n} • +5 coins`)}}
function openCreate(){document.querySelector('#create').showModal()}
function createChallenge(){let title=document.querySelector('#title').value.trim(),desc=document.querySelector('#desc').value.trim(),friend=document.querySelector('#friend').value.trim();if(!title)return alert('Add a title');challenges.unshift({id:Date.now(),user:'You',to:friend||'Friends',title,desc:(document.querySelector('#type').value+' • '+(desc||'Beat this challenge!')),likes:0,dislikes:0,comments:0,attempts:0,chain:1,trending:false});coins+=10;save();render();document.querySelector('#create').close();alert('Challenge created • +10 coins')}
function filterFeed(x){render(x==='trending'?challenges.filter(c=>c.trending):challenges)}
function showShop(){document.querySelector('#items').innerHTML=shopItems.map((x,i)=>`<div class='shopitem'><span>${x[0]}<br><small>${x[2]}</small></span><button onclick='buy(${i})'>🪙 ${x[1]}</button></div>`).join('');document.querySelector('#shop').showModal()}
function buy(i){let x=shopItems[i];if(coins<x[1])return alert('Not enough coins');coins-=x[1];owned.push({item:x[0],duration:x[2],bought:Date.now()});save();alert(x[0]+' unlocked! 🔓')}
save();render();
